// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Te02AObkjF-vECNXAKbgQouLYfy6mRM',
    appId: '1:422110889291:web:6a7ce363d9ea32de52d4ce',
    messagingSenderId: '422110889291',
    projectId: 'app-movie-df089',
    authDomain: 'app-movie-df089.firebaseapp.com',
    storageBucket: 'app-movie-df089.firebasestorage.app',
    measurementId: 'G-4MDHV92PRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZ3CTraB_NWI_O4A8zwRlmhhpdqqt9Is',
    appId: '1:422110889291:android:1cfc5f1f8c5c40c452d4ce',
    messagingSenderId: '422110889291',
    projectId: 'app-movie-df089',
    storageBucket: 'app-movie-df089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBVnA_qGoLFfaF1A907x8BUkZlGnIikzw',
    appId: '1:422110889291:ios:f102f70b8e61c6ca52d4ce',
    messagingSenderId: '422110889291',
    projectId: 'app-movie-df089',
    storageBucket: 'app-movie-df089.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBVnA_qGoLFfaF1A907x8BUkZlGnIikzw',
    appId: '1:422110889291:ios:f102f70b8e61c6ca52d4ce',
    messagingSenderId: '422110889291',
    projectId: 'app-movie-df089',
    storageBucket: 'app-movie-df089.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Te02AObkjF-vECNXAKbgQouLYfy6mRM',
    appId: '1:422110889291:web:88f5d93a035a300452d4ce',
    messagingSenderId: '422110889291',
    projectId: 'app-movie-df089',
    authDomain: 'app-movie-df089.firebaseapp.com',
    storageBucket: 'app-movie-df089.firebasestorage.app',
    measurementId: 'G-8Z7260Q1F5',
  );

}

